// Code generated by builder-gen. DO NOT EDIT.
package network

func (o Opts) HasDialer() bool {
	return o.Dialer != nil
}

type OptsFunc func(*Opts)

func ToOpts(opts ...OptsFunc) Opts {
	var info Opts
	ToOptsWithDefault(&info, opts...)

	return info
}

func ToOptsWithDefault(info *Opts, opts ...OptsFunc) {
	for _, o := range opts {
		o(info)
	}
}

func WithDialer(dialerParam Dialer) OptsFunc {
	return func(opts *Opts) {
		opts.Dialer = &dialerParam
	}
}
