// Code generated by builder-gen. DO NOT EDIT.
package grabber

func (o GetAddressValueOpts) HasAddressMap() bool {
	return o.AddressMap != nil
}

func (o GetAddressValueOpts) HasIgnoreUnknownSpenders() bool {
	return o.IgnoreUnknownSpenders != nil
}

type GetAddressValueOptsFunc func(*GetAddressValueOpts)

func ToGetAddressValueOpts(opts ...GetAddressValueOptsFunc) GetAddressValueOpts {
	var info GetAddressValueOpts
	ToGetAddressValueOptsWithDefault(&info, opts...)

	return info
}

func ToGetAddressValueOptsWithDefault(info *GetAddressValueOpts, opts ...GetAddressValueOptsFunc) {
	for _, o := range opts {
		o(info)
	}
}

func AddressMapForGetAddressValue(addressMapParam AddressMap) GetAddressValueOptsFunc {
	return func(opts *GetAddressValueOpts) {
		opts.AddressMap = &addressMapParam
	}
}

func IgnoreUnknownSpendersForGetAddressValue(ignoreUnknownSpendersParam bool) GetAddressValueOptsFunc {
	return func(opts *GetAddressValueOpts) {
		opts.IgnoreUnknownSpenders = &ignoreUnknownSpendersParam
	}
}
