// Code generated by builder-gen. DO NOT EDIT.
package mempoolspace

import (
	"net/http"

	"github.com/btcsuite/btcd/chaincfg"
)

func (o RestOpts) HasHttpClient() bool {
	return o.HttpClient != nil
}

func (o RestOpts) HasNetwork() bool {
	return o.Network != nil
}

type RestOptsFunc func(*RestOpts)

func ToRestOpts(opts ...RestOptsFunc) RestOpts {
	var info RestOpts
	ToRestOptsWithDefault(&info, opts...)

	return info
}

func ToRestOptsWithDefault(info *RestOpts, opts ...RestOptsFunc) {
	for _, o := range opts {
		o(info)
	}
}

func WithHttpClient(httpClientParam http.Client) RestOptsFunc {
	return func(opts *RestOpts) {
		opts.HttpClient = &httpClientParam
	}
}

func WithNetwork(networkParam *chaincfg.Params) RestOptsFunc {
	return func(opts *RestOpts) {
		opts.Network = &networkParam
	}
}
